"""Real two-connection payment races; accepts only the named local test stack.

python3 supabase/tests/database/payment_concurrency.py
Fixtures use random UUIDs and are deleted in finally; never use a remote DB.
"""
import concurrent.futures
import subprocess
import uuid

CONTAINER = "supabase_db_psi_payments_20260911"
CMD = ["docker", "exec", "-i", CONTAINER, "psql", "-X", "-qAt", "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "postgres"]


def sql(query):
    result = subprocess.run(CMD, input=query, text=True, capture_output=True, check=True)
    return [line for line in result.stdout.splitlines() if line]


def race(query_a, query_b=None):
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as pool:
        a = pool.submit(sql, query_a)
        b = pool.submit(sql, query_b or query_a)
        return a.result(), b.result()


user_id, profile_id, subscription_id = (str(uuid.uuid4()) for _ in range(3))
try:
    sql(f"""
    insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data)
    values ('{user_id}','authenticated','authenticated','concurrency-{user_id}@example.invalid','{{}}','{{}}');
    insert into private.legal_acceptances(user_id,document_type,document_version)
    select '{user_id}',document_type,version from private.legal_document_versions where is_current;
    insert into public.professional_profiles(id,user_id,slug,first_name,last_name,headline,bio,is_demo)
    values ('{profile_id}','{user_id}','concurrency-{profile_id}','Prueba','Pagos',
      'Perfil prueba concurrencia','Perfil de prueba de pagos aislado y sin publicación.',true);
    """)
    selected_a, selected_b = race(f"""begin;
    set local role authenticated;
    select set_config('request.jwt.claim.sub','{user_id}',true);
    select public.select_professional_plan('{profile_id}','PROFESSIONAL_MONTHLY');
    select pg_sleep(0.3); commit;""")
    # Each query prints claim UID followed by subscription ID.
    assert selected_a[1] == selected_b[1], (selected_a, selected_b)
    subscription_id = selected_a[1]
    assert sql(f"select count(*) from public.subscriptions where professional_profile_id='{profile_id}';") == ['1']
    print("PASS: concurrent plan selection returns one pending subscription")

    reserved_a, reserved_b = race(f"""begin;
    select public.begin_subscription_checkout(id,'personal',plan_snapshot)
    from public.subscriptions where id='{subscription_id}';
    select pg_sleep(0.3); commit;""")
    assert sorted([reserved_a[0], reserved_b[0]]) == ['f', 't'], (reserved_a, reserved_b)
    print("PASS: concurrent checkout reservations allow exactly one provider POST")

    sql(f"""select public.attach_subscription_checkout(id,'personal','race-{subscription_id}',null,plan_snapshot)
    from public.subscriptions where id='{subscription_id}';""")
    payment_query = f"""begin;
    select public.apply_subscription_payment_event('race-{subscription_id}','same-event','approved',
    '2026-09-01','{{}}','2026-09-01','personal','{subscription_id}',120000,'ARS',
    'subscription_authorized_payment','race-payment-{subscription_id}');
    select pg_sleep(0.3); commit;"""
    applied_a, applied_b = race(payment_query)
    assert sorted([applied_a[0], applied_b[0]]) == ['f', 't'], (applied_a, applied_b)
    assert sql(f"select count(*) from private.subscription_events where subscription_id='{subscription_id}';") == ['1']
    assert sql(f"select status || ':' || current_period_end::date from public.subscriptions where id='{subscription_id}';") == ['ACTIVE:2026-10-01']
    print("PASS: concurrent duplicate payment commits one event and one paid period")

    def transition(event, status, occurred, paid):
        return f"""begin;
        select public.apply_subscription_payment_event('race-{subscription_id}','{event}','{status}',
        {paid},'{{"date_created":"2026-10-01"}}','{occurred}','personal','{subscription_id}',120000,'ARS',
        'subscription_authorized_payment','race-next-payment-{subscription_id}');
        select pg_sleep(0.3); commit;"""

    race(transition('rejected', 'rejected', '2026-10-01', 'null'),
         transition('approved', 'approved', '2026-10-02', "'2026-10-02'"))
    assert sql(f"select status || ':' || current_period_end::date from public.subscriptions where id='{subscription_id}';") == ['ACTIVE:2026-11-02']
    print("PASS: concurrent rejection/approval converges to newest paid state")
finally:
    # Restricted to random IDs generated by this test in the local test stack.
    sql(f"""begin;
    delete from private.subscription_events where subscription_id in (select id from public.subscriptions where professional_profile_id='{profile_id}');
    delete from private.subscription_payment_receipts where subscription_id in (select id from public.subscriptions where professional_profile_id='{profile_id}');
    delete from private.subscription_payment_state where subscription_id in (select id from public.subscriptions where professional_profile_id='{profile_id}');
    delete from public.subscriptions where professional_profile_id='{profile_id}';
    delete from public.professional_profiles where id='{profile_id}';
    delete from auth.users where id='{user_id}';
    commit;""")
